server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: KJM
    password: TIGER
    
 

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 445171505301-ear946151chlu3017kvtebirc7j6kvok.apps.googleusercontent.com
            client-secret: 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 
            scope:
            - email
            - profile
          
          facebook:
            client-id: 844673032896066
            client-secret: 5c853c37b5d25620dc2b17a3d39836d4 
            scope:
            - email
            - public_profile
          
          naver:
            client-id: PUagw7A5RUP8v3U8OmHV
            client-secret: pM10WeUWin
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:80/login/oauth2/code/naver
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데 response라는 키 값으로 naver가 리턴해줌
            
            
            
          
            
          
           
            
         
            
          




